- name: Welcome New Users
  # You may pin to the exact commit or the version.
  # uses: bubkoo/welcome-action@8dbbac2540d155744c90e4e37da6b05ffc9c5e2c
  uses: bubkoo/welcome-action@v1.0.3
  with:
    # Your GitHub token for authentication.
    GITHUB_TOKEN: 
    # Comment to be posted to on first time issues.
    FIRST_ISSUE: # optional
    # Comment to be posted to on first time issues.
    FIRST_ISSUE_COMMENT: # optional
    # Reactions to be add to comment on first time issues.
    FIRST_ISSUE_REACTIONS: # optional
    # Comment to be posted to on PRs from first time contributors in your repository.
    FIRST_PR: # optional
    # Comment to be posted to on PRs from first time contributors in your repository.
    FIRST_PR_COMMENT: # optional
    # Reactions to be add to comment on PRs from first time contributors in your repository.
    FIRST_PR_REACTIONS: # optional
    # Comment to be posted to on pull requests merged by a first time user.
    FIRST_PR_MERGED: # optional
    # Comment to be posted to on pull requests merged by a first time user.
    FIRST_PR_MERGED_COMMENT: # optional
    # Reactions to be add to comment on pull requests merged by a first time user.
    FIRST_PR_MERGED_REACTIONS: # optional
